from __future__ import annotations

import datetime as dt
import math
import re
import shlex
import subprocess
import tempfile
from dataclasses import dataclass
from pathlib import Path
from typing import Callable, Optional

from PySide6.QtGui import QImage


@dataclass
class KapReference:
    pixel_x: float
    pixel_y: float
    lon: float
    lat: float


@dataclass
class KapPolygonPoint:
    pixel_x: float
    pixel_y: float
    lon: float
    lat: float


@dataclass
class KapExportJob:
    sheet_name: str
    image_path: Path
    output_path: Path
    width: int
    height: int
    scale: int
    polygon: list[KapPolygonPoint]
    references: list[KapReference]


@dataclass
class KapExportResult:
    sheet_name: str
    output_path: Path
    success: bool
    error: str = ""
    stdout: str = ""
    stderr: str = ""


def sanitize_kap_stem(name: str, fallback: str = "sheet") -> str:
    candidate = re.sub(r"[^A-Za-z0-9._-]+", "_", (name or "").strip()).strip("._-")
    return candidate or fallback


def _build_header(
    job: KapExportJob,
    ed_date: str,
    sounding_unit: str,
    sounding_datum: str,
) -> str:
    # Keep compatibility with existing imgkap workflow: PP and REF/PLY use lat,lon order.
    projection_param = sum(p.lat for p in job.polygon) / len(job.polygon)
    lines: list[str] = []
    lines.append("! Converted from pymapcal project")
    lines.append("! Generated by kap_export.py")
    lines.append("VER/2.0")
    lines.append(f"BSB/NA={job.sheet_name}")
    lines.append("    NU=1")
    lines.append(f"    RA={job.width},{job.height},DU=")
    lines.append(f"KNP/SC={job.scale},GD=WGS84,PR=MERCATOR")
    lines.append(f"    PP={projection_param:.8f},PI=UNKNOWN,SP=UNKNOWN,SK=0.0")
    lines.append(f"    UN={sounding_unit.upper()},SD={sounding_datum},DX=000,DY=000")
    lines.append(f"CED/SE=,RE=,ED={ed_date}")

    ref_no = 1
    for p in job.polygon:
        lines.append(
            f"REF/{ref_no},{_fmt_pixel(p.pixel_x)},{_fmt_pixel(p.pixel_y)},{p.lat:.10f},{p.lon:.10f}"
        )
        ref_no += 1
    for p in job.references:
        lines.append(
            f"REF/{ref_no},{_fmt_pixel(p.pixel_x)},{_fmt_pixel(p.pixel_y)},{p.lat:.10f},{p.lon:.10f}"
        )
        ref_no += 1

    for idx, p in enumerate(job.polygon, start=1):
        lines.append(f"PLY/{idx},{p.lat:.10f},{p.lon:.10f}")

    lines.append("DTM/0,0")
    return "\n".join(lines) + "\n"


def _fmt_pixel(value: float) -> str:
    rounded = round(value)
    if abs(value - rounded) < 1e-7:
        return str(int(rounded))
    return f"{value:.6f}".rstrip("0").rstrip(".")


def run_kap_export_jobs(
    jobs: list[KapExportJob],
    imgkap_path: str = "imgkap",
    palette: str = "NONE",
    ed_date: Optional[str] = None,
    sounding_unit: str = "Meters",
    sounding_datum: str = "UNKNOWN",
    temp_dir: Optional[Path] = None,
    log_path: Optional[Path] = None,
    progress_cb: Optional[Callable[[int, int, str], None]] = None,
    cancel_requested_cb: Optional[Callable[[], bool]] = None,
) -> list[KapExportResult]:
    date_text = ed_date or dt.date.today().strftime("%m/%d/%Y")
    results: list[KapExportResult] = []
    normalized_cache: dict[Path, Path] = {}
    temp_images: list[Path] = []
    total_jobs = len(jobs)
    if progress_cb is not None:
        try:
            progress_cb(0, total_jobs, "-")
        except Exception:
            pass
    keep_temps = temp_dir is not None
    if temp_dir is not None:
        temp_dir.mkdir(parents=True, exist_ok=True)
        if log_path is None:
            log_path = temp_dir / "imgkap_calls.log"

    processed = 0
    for job in jobs:
        if cancel_requested_cb is not None and cancel_requested_cb():
            _append_log(
                log_path,
                f"[{_now_ts()}] CANCEL requested before next job start\n",
            )
            break
        header_path: Optional[Path] = None
        sheet_prefix = f"{sanitize_kap_stem(job.sheet_name, fallback='sheet')}_"
        cancelled_now = False
        try:
            source_image: Path
            if keep_temps:
                # Keep per-sheet artifacts in debug mode so file names clearly map to a sheet.
                source_image = _normalize_to_png(
                    job.image_path,
                    temp_dir=temp_dir,
                    prefix=f"{sheet_prefix}src_",
                )
                if source_image != job.image_path:
                    temp_images.append(source_image)
            else:
                source_image = normalized_cache.get(job.image_path)  # type: ignore[assignment]
                if source_image is None:
                    source_image = _normalize_to_png(
                        job.image_path,
                        temp_dir=temp_dir,
                        prefix=f"{sheet_prefix}src_",
                    )
                    normalized_cache[job.image_path] = source_image
                    if source_image != job.image_path:
                        temp_images.append(source_image)

            working_job = job
            crop_box = _compute_crop_box(job)
            full_box = (0, 0, job.width, job.height)
            working_image = source_image
            if crop_box != full_box:
                cropped_image = _crop_image(
                    source_image,
                    crop_box,
                    temp_dir=temp_dir,
                    prefix=f"{sheet_prefix}crop_",
                )
                if cropped_image is None:
                    raise RuntimeError(f"crop_failed: {job.image_path}")
                working_image = cropped_image
                temp_images.append(cropped_image)
                working_job = _apply_crop_transform(job, crop_box)
                _append_log(
                    log_path,
                    (
                        f"[{_now_ts()}] CROP sheet={job.sheet_name} "
                        f"box={crop_box[0]},{crop_box[1]}->{crop_box[2]-1},{crop_box[3]-1} "
                        f"size={working_job.width}x{working_job.height}\n"
                    ),
                )

            header_text = _build_header(working_job, date_text, sounding_unit, sounding_datum)
            header_path = _new_temp_path(".txt", f"{sheet_prefix}hdr_", temp_dir=temp_dir)
            header_path.write_text(header_text, encoding="utf-8")

            cmd = [
                imgkap_path,
                "-p",
                palette,
                str(working_image),
                str(header_path),
                str(job.output_path),
            ]
            _append_log(
                log_path,
                f"[{_now_ts()}] START sheet={job.sheet_name} cmd={_format_cmd(cmd)}\n",
            )
            rc, stdout, stderr, cancelled_now = _run_command_cancellable(
                cmd,
                cancel_requested_cb=cancel_requested_cb,
            )
            _append_log(
                log_path,
                (
                    f"[{_now_ts()}] END sheet={job.sheet_name} rc={rc} cancelled={cancelled_now}\n"
                    f"stdout:\n{stdout}\n"
                    f"stderr:\n{stderr}\n"
                ),
            )
            if cancelled_now:
                results.append(
                    KapExportResult(
                        sheet_name=job.sheet_name,
                        output_path=job.output_path,
                        success=False,
                        error="cancelled",
                        stdout=stdout.strip(),
                        stderr=stderr.strip(),
                    )
                )
            elif rc == 0 and job.output_path.exists():
                results.append(
                    KapExportResult(
                        sheet_name=job.sheet_name,
                        output_path=job.output_path,
                        success=True,
                        stdout=stdout.strip(),
                        stderr=stderr.strip(),
                    )
                )
            else:
                results.append(
                    KapExportResult(
                        sheet_name=job.sheet_name,
                        output_path=job.output_path,
                        success=False,
                        error="imgkap_failed" if rc != 0 else "kap_not_created",
                        stdout=stdout.strip(),
                        stderr=stderr.strip(),
                    )
                )
        except FileNotFoundError:
            _append_log(
                log_path,
                f"[{_now_ts()}] ERROR sheet={job.sheet_name} imgkap_not_found path={imgkap_path}\n",
            )
            results.append(
                KapExportResult(
                    sheet_name=job.sheet_name,
                    output_path=job.output_path,
                    success=False,
                    error="imgkap_not_found",
                )
            )
        except Exception as exc:  # pragma: no cover
            _append_log(
                log_path,
                f"[{_now_ts()}] ERROR sheet={job.sheet_name} exception={exc}\n",
            )
            results.append(
                KapExportResult(
                    sheet_name=job.sheet_name,
                    output_path=job.output_path,
                    success=False,
                    error=str(exc),
                )
            )
        finally:
            if header_path is not None and not keep_temps:
                try:
                    header_path.unlink(missing_ok=True)
                except OSError:
                    pass
        processed += 1
        if progress_cb is not None:
            try:
                progress_cb(processed, total_jobs, job.sheet_name)
            except Exception:
                pass
        if cancelled_now:
            break
    if not keep_temps:
        for temp_img in temp_images:
            try:
                temp_img.unlink(missing_ok=True)
            except OSError:
                pass

    return results


def _normalize_to_png(
    image_path: Path,
    temp_dir: Optional[Path] = None,
    prefix: str = "pymapcal_src_",
    ) -> Path:
    qimg = QImage(str(image_path))
    if qimg.isNull():
        return image_path
    rgb = qimg.convertToFormat(QImage.Format_RGB888)
    out = _new_temp_path(".png", prefix, temp_dir=temp_dir)
    if not rgb.save(str(out), "PNG"):
        try:
            out.unlink(missing_ok=True)
        except OSError:
            pass
        return image_path
    return out


def _compute_crop_box(job: KapExportJob) -> tuple[int, int, int, int]:
    width = int(job.width)
    height = int(job.height)
    xs = [p.pixel_x for p in job.polygon]
    ys = [p.pixel_y for p in job.polygon]
    left = max(0, min(width - 1, int(math.floor(min(xs)))))
    top = max(0, min(height - 1, int(math.floor(min(ys)))))
    right = min(width, max(left + 1, int(math.ceil(max(xs))) + 1))
    bottom = min(height, max(top + 1, int(math.ceil(max(ys))) + 1))
    return left, top, right, bottom


def _apply_crop_transform(job: KapExportJob, crop_box: tuple[int, int, int, int]) -> KapExportJob:
    left, top, right, bottom = crop_box
    polygon = [
        KapPolygonPoint(
            pixel_x=p.pixel_x - left,
            pixel_y=p.pixel_y - top,
            lon=p.lon,
            lat=p.lat,
        )
        for p in job.polygon
    ]
    references = [
        KapReference(
            pixel_x=p.pixel_x - left,
            pixel_y=p.pixel_y - top,
            lon=p.lon,
            lat=p.lat,
        )
        for p in job.references
    ]
    return KapExportJob(
        sheet_name=job.sheet_name,
        image_path=job.image_path,
        output_path=job.output_path,
        width=right - left,
        height=bottom - top,
        scale=job.scale,
        polygon=polygon,
        references=references,
    )


def _crop_image(
    image_path: Path,
    crop_box: tuple[int, int, int, int],
    temp_dir: Optional[Path] = None,
    prefix: str = "pymapcal_crop_",
) -> Optional[Path]:
    left, top, right, bottom = crop_box
    qimg = QImage(str(image_path))
    if qimg.isNull():
        return None
    cropped = qimg.copy(left, top, right - left, bottom - top).convertToFormat(QImage.Format_RGB888)
    out = _new_temp_path(".png", prefix, temp_dir=temp_dir)
    if not cropped.save(str(out), "PNG"):
        try:
            out.unlink(missing_ok=True)
        except OSError:
            pass
        return None
    return out


def _new_temp_path(suffix: str, prefix: str, temp_dir: Optional[Path]) -> Path:
    with tempfile.NamedTemporaryFile(
        suffix=suffix,
        prefix=prefix,
        dir=str(temp_dir) if temp_dir is not None else None,
        delete=False,
    ) as tmp:
        return Path(tmp.name)


def _format_cmd(cmd: list[str]) -> str:
    return " ".join(shlex.quote(part) for part in cmd)


def _append_log(log_path: Optional[Path], text: str) -> None:
    if log_path is None:
        return
    try:
        log_path.parent.mkdir(parents=True, exist_ok=True)
        with log_path.open("a", encoding="utf-8") as f:
            f.write(text)
    except OSError:
        pass


def _now_ts() -> str:
    return dt.datetime.now().isoformat(timespec="seconds")


def _run_command_cancellable(
    cmd: list[str],
    cancel_requested_cb: Optional[Callable[[], bool]] = None,
) -> tuple[int, str, str, bool]:
    proc = subprocess.Popen(
        cmd,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        text=True,
    )
    cancelled = False
    while True:
        try:
            stdout, stderr = proc.communicate(timeout=0.1)
            rc = proc.returncode if proc.returncode is not None else -1
            return rc, stdout or "", stderr or "", cancelled
        except subprocess.TimeoutExpired:
            if cancel_requested_cb is None or not cancel_requested_cb():
                continue
            cancelled = True
            proc.terminate()
            try:
                stdout, stderr = proc.communicate(timeout=2.0)
            except subprocess.TimeoutExpired:
                proc.kill()
                stdout, stderr = proc.communicate()
            rc = proc.returncode if proc.returncode is not None else -1
            return rc, stdout or "", stderr or "", cancelled
